
## main setting

windowName: 'draw_pad'
testFile: 'test1.png'
quitKey: 'q'

## brush

brush:
  radius: 2
  b: 0
  g: 0
  r: 0

## laplacian setting

laplacian_smoothing:
  iter: 10
  lambda: 0.5

## optimization

optimization:
  local:
    threshold: 0.2
    circle_sampling: 100
    radius: 15