
## main setting

windowName: 'draw_pad'
testFile: 'test2.jpg'
quitKey: 'q'

## brush

brush:
  radius: 1
  b: 0
  g: 0
  r: 0

## laplacian setting

laplacian_smoothing:
  iter: 10
  lambda: 0.5

## optimization

optimization:
  local:
    threshold: 0.05
    circle_sampling: 100
    radius: 5
    sigma_m: 0.5 # 0.5 to 2.0
    sigma_c: 1 # 1 to 3
    sigma_s: 1.6 # 1.6x of sigma_c
    rho: 0.5 # 0.5 to 2.0
    balancing_weight: 0.5 # weight of filter response
    edge_weight_limit: 0.07 # limit of